version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      args:
            user: iischenko # your username on your machine, you can get it by running echo $USER
            uid: 1000 # your uid which you can get by running id -u
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: project_app